### ISSUE TITLE
Ambiguous wording made it sound like the palace ate cows

### ISSUE THREAD

**Issue by pomatias** [dryack/go-hamurabi#3]
In year 9, I saw the following: 

```My Lord, your workers have completed work on your palace!
You are residing in a large palace, together with your family and closest retainers.
As we lacked the land to support them, 3 cows were slaughtered!```

I initially read this as having insufficient land to support the palace, family, and retainers causing the cows to be slaughtered, and complained that my palace ate my cows. 

Upon further reflection it seems that the cows experienced perfectly normal starvation due to my land quantity being at 0. However, the wording of the cows thing was confusing when I saw it the first time.


```
$ git show
commit 56f59340ef58ab409f5a46ade1ba4d90de583bf9 (HEAD -> refactor, origin/refactor)

$ ./Hamurabi 
How many turns would you like to play? [10] => 999

Oh great Hamurabi, congratulations on your accession to the rule of our beautiful Sumer! I am here to provide you with the knowledge you need to help us thrive.
<ENTER> to continue

Each year I will present you with an accounting of our prior year's incomes and expenditures. 
I will explain the manner in which our population changed, the number of acres of land we hold, the number of cows we have available to help feed our population, and how many people they fed. 
In addition I will tell you the number of bushels of barley we reaped per acre of planted land. Finally I will inform you of the toll taken on our grain reserves by the rats.
<ENTER> to continue

Oh dread lord Hamurabi, I beg you to know our people each require 20 bushels of grain a year or else they will starve. 
The milk, butter, and cheese provided by our cows will feed 15 people a year for each cow, but no income is gained in this way. Cows require 3 acres of land each on which to graze.
During hard times, you may order the slaughter of cows, and in this way feed many people.
<ENTER> to continue

Acres may be purchased from land-owning peasants at a price which varies each year. 
Our people may only plant 10 acres of land each, although we have great hopes that our strongest men may come to plant more as we begin to make use of hand plows.
Too much land untended by peasants is liable to be reclaimed by nature.
Our priests tell us that Enki has delivered unto them the plans for a building that will protect our barley from the rats, but warn construction will be expensive.
Plows multiplythe labor of our adult male peasants, freeing others to trade and craft. This may have significant impact onour income.<ENTER> to continue

You must know that starvation; whether caused by cruelty, plague, or pest, will eventually lead to the people rising up and deposing you. 
Sometimes it is best to let some starve today, in the hope that the gods and your steady hand will feed us all in the future. And now my lord, you are ready to rule!
<ENTER> to continue

My lord, in the year 0, I beg to report to you that 0 people starved, 0 were born, and 0 came to the city.
Population is now 100.
The city owns 1000 acres of land, and has 0 granaries.
The city keeps 0 cows whose product fed 0 people this year.
Traders report that Ur harvested 3 bushels per acrs.
Rats ate 200 bushels of grain.
We now have 2800 bushels in store.
We have distributed a total of 0 hand plows amongst the people.
Land is trading at 20 bushels per acre.
How many acres do you wish to buy? [0] => 
How many acres do you wish to sell? [0] => 500
You have 12800 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => y
Do you wish to order the construction of city granaries for 500 bushels, each are able to protect a large amount of precious barley? [0] => 4
You have 10800 bushels of grain remaining.
Lord shall we begin construction on a palace at a cost of 10000 (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 10
You have 9800 bushels of grain remaining.
How many bushels do you wish to release to your people? [2000] => 1500
You have 8300 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [500] => 
You have 7800 bushels of grain remaining.

My lord, in the year 1, I beg to report to you that 25 people starved, 16 were born, and 2 came to the city.
Population is now 93.
The city owns 500 acres of land, and has 4 granaries.
The city keeps 0 cows whose product fed 0 people this year.
We have harvested 9 bushels per acre.
Thanks to having 65 citizens not required to farm, trade goods and vegatables brought in 130 bushels of grain.
Rats ate 0 bushels of grain.
We now have 12430 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 17 bushels per acre.
How many acres do you wish to buy? [0] => 500
You have 3930 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => n
Have you gone mad Hamurabi?! Try again.
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1860] => 1400
You have 2530 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [980] => 
You have 1550 bushels of grain remaining.

My lord, in the year 2, I beg to report to you that 23 people starved, 10 were born, and 6 came to the city.
Population is now 86.
The city owns 1000 acres of land, and has 4 granaries.
The city keeps 0 cows whose product fed 0 people this year.
We have harvested 1 bushels per acre.
Thanks to having 65 citizens not required to farm, trade goods and vegatables brought in 390 bushels of grain.
Rats ate 0 bushels of grain.
We now have 2920 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 19 bushels per acre.
How many acres do you wish to buy? [0] => 
How many acres do you wish to sell? [0] => 100
You have 4820 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1720] => 1300
You have 3520 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [900] => 
You have 2620 bushels of grain remaining.

My lord, in the year 3, I beg to report to you that 21 people starved, 12 were born, and 2 came to the city.
Population is now 79.
The city owns 900 acres of land, and has 4 granaries.
The city keeps 0 cows whose product fed 0 people this year.
We have harvested 5 bushels per acre.
Thanks to having 11 citizens not required to farm, trade goods and vegatables brought in 88 bushels of grain.
Rats ate 0 bushels of grain.
We now have 7208 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 19 bushels per acre.
How many acres do you wish to buy? [0] => 
How many acres do you wish to sell? [0] => 
My lord, do you wish to consider construction projects this year (y,n)? => 
My lord you are incoherent, I need a yes or no to proceed!
My lord, do you wish to consider construction projects this year (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1580] => 1100
You have 6108 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [840] => 
You have 5268 bushels of grain remaining.

My lord, in the year 4, I beg to report to you that 24 people starved, 19 were born, and 0 came to the city.
Population is now 74.
The city owns 900 acres of land, and has 4 granaries.
The city keeps 0 cows whose product fed 0 people this year.
We have harvested 4 bushels per acre.
Thanks to having 11 citizens not required to farm, trade goods and vegatables brought in 33 bushels of grain.
Rats ate 0 bushels of grain.
We now have 8661 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 23 bushels per acre.
How many acres do you wish to buy? [0] => 
How many acres do you wish to sell? [0] => 400
You have 17861 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => y
Do you wish to order the construction of city granaries for 2500 bushels, each are able to protect a large amount of precious barley? [0] => 
Lord shall we begin construction on a palace at a cost of 10000 (y,n)? => y
You have 7861 bushels of grain remaining.
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1480] => 1100
You have 6761 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [500] => 
You have 6261 bushels of grain remaining.

My lord, in the year 5, I beg to report to you that 19 people starved, 10 were born, and 1 came to the city.
Population is now 66.
The city owns 500 acres of land, and has 4 granaries.
Construction on your palace is underway, and will be completed in 4 years.
The city keeps 0 cows whose product fed 0 people this year.
We have harvested 9 bushels per acre.
Thanks to having 39 citizens not required to farm, trade goods and vegatables brought in 429 bushels of grain.
Rats ate 0 bushels of grain.
We now have 11190 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 26 bushels per acre.
How many acres do you wish to buy? [0] => 
How many acres do you wish to sell? [0] => 500
You have 24190 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => y
Do you wish to order the construction of city granaries for 2500 bushels, each are able to protect a large amount of precious barley? [0] => 
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1320] => 1000
You have 23190 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 3
You have 20190 bushels of grain remaining.
How many fields will you plant? [0] => 
However your personal retainers protected your personal estate!

My lord, in the year 6, I beg to report to you that 16 people starved, 9 were born, and 0 came to the city.
Population is now 59.
The city owns 500 acres of land, and has 4 granaries.
Construction on your palace is underway, and will be completed in 3 years.
As we lacked the land to support them, 3 cows were slaughtered!
The city keeps 0 cows whose product fed 0 people this year.
Traders report that Lagash harvested 5 bushels per acrs.
Thanks to having 81 citizens not required to farm, trade goods and vegatables brought in 2430 bushels of grain.
Rats ate 2047 bushels of grain.
We now have 20573 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 22 bushels per acre.
How many acres do you wish to buy? [0] => 100
You have 18373 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1180] => 1000
You have 17373 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [600] => 
You have 16773 bushels of grain remaining.

My lord, in the year 7, I beg to report to you that 9 people starved, 29 were born, and 2 came to the city.
Population is now 81.
The city owns 600 acres of land, and has 4 granaries.
Construction on your palace is underway, and will be completed in 2 years.
As we lacked the land to support them, 3 cows were slaughtered!
The city keeps 0 cows whose product fed 0 people this year.
We have harvested 1 bushels per acre.
Thanks to having 14 citizens not required to farm, trade goods and vegatables brought in 28 bushels of grain.
Rats ate 1193 bushels of grain.
We now have 16208 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 24 bushels per acre.
How many acres do you wish to buy? [0] => 
How many acres do you wish to sell? [0] => 
My lord, do you wish to consider construction projects this year (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1620] => 1300
You have 14908 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [600] => 
You have 14308 bushels of grain remaining.

My lord, in the year 8, I beg to report to you that 16 people starved, 11 were born, and 5 came to the city.
Population is now 81.
The city owns 600 acres of land, and has 4 granaries.
Construction on your palace is underway, and will be completed in 1 years.
As we lacked the land to support them, 3 cows were slaughtered!
The city keeps 0 cows whose product fed 0 people this year.
We have harvested 5 bushels per acre.
Thanks to having 36 citizens not required to farm, trade goods and vegatables brought in 1404 bushels of grain.
Rats ate 577 bushels of grain.
We now have 18135 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 26 bushels per acre.
How many acres do you wish to buy? [0] => 
How many acres do you wish to sell? [0] => 600
You have 33735 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => y
Do you wish to order the construction of city granaries for 2500 bushels, each are able to protect a large amount of precious barley? [0] => 12
You have 3735 bushels of grain remaining.
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1620] => 1300
You have 2435 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [0] => 
However your personal retainers protected your personal estate!

My lord, in the year 9, I beg to report to you that 16 people starved, 16 were born, and 6 came to the city.
Population is now 87.
The city owns 500 acres of land, and has 16 granaries.
My Lord, your workers have completed work on your palace!
You are residing in a large palace, together with your family and closest retainers.
As we lacked the land to support them, 3 cows were slaughtered!
The city keeps 0 cows whose product fed 0 people this year.
Traders report that Lagash harvested 7 bushels per acrs.
Thanks to having 96 citizens not required to farm, trade goods and vegatables brought in 4416 bushels of grain.
Rats ate 0 bushels of grain.
We now have 6851 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 20 bushels per acre.
How many acres do you wish to buy? [0] => 100
You have 4851 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [1740] => 1300
You have 3551 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 2
You have 1551 bushels of grain remaining.
How many fields will you plant? [594] => 
You have 957 bushels of grain remaining.

My lord, in the year 10, I beg to report to you that 0 people starved, 43 were born, and 10 came to the city.
Population is now 140.
The city owns 600 acres of land, and has 16 granaries.
You are residing in a large palace, together with your family and closest retainers.
As we lacked the land to support them, 3 cows were slaughtered!
The city keeps 2 cows whose product fed 30 people this year.
We have harvested 1 bushels per acre.
Thanks to having 43 citizens not required to farm, trade goods and vegatables brought in 860 bushels of grain.
Rats ate 0 bushels of grain.
We now have 2405 bushels in store.
We have distributed a total of 10 hand plows amongst the people.
Land is trading at 20 bushels per acre.
How many acres do you wish to buy? [0] => 100
You have 405 bushels of grain remaining.
My lord, do you wish to consider construction projects this year (y,n)? => n
Do you wish to order the purchase of plows for 100 bushels, these will make it easier for your people to plant the fields? [0] => 
How many bushels do you wish to release to your people? [405] => 
You have 0 bushels of grain remaining.
How many cows would you like to slaughter in order to feed 35 people? [0] => 
How many cows will you purchase, at 1000 bushels per cow? [0] => 
How many fields will you plant? [0] => 

You starved 90 out of your population of only 140, this has caused you to be deposed by force!
In your 11 year reign 5 percent of the population starved per year on average. A total of 259 people died during your reign.
The city began with 100 citizens and ended with 140.
You ordered the building of 16 granaries during your rule.
The city began with 10 acres per person and ended with 5.
We maintained a herd of 2 cows.
	Avg Bushels at turn start: 106; Avg Bushels eaten by rats: 3```

**Comment by dryack** [comment]
Fixed in https://github.com/dryack/go-hamurabi/commit/d15807d3cd43bd857a2ba1a2460a56d4fdfa75be
