### ISSUE TITLE
termenv-devel won't build

### ISSUE THREAD

**Issue by pomatias** [dryack/go-hamurabi#6]
```
$ git show
commit 0a001e2ceae771bb4f93181c4ebf060a868838d6 (HEAD -> termenv-devel, origin/termenv-devel)
...
$ go build
interface.go:6:2: missing go.sum entry for module providing package github.com/mattn/go-tty (imported by Hamurabi); to add:
	go get Hamurabi
interface.go:7:2: missing go.sum entry for module providing package github.com/muesli/termenv (imported by Hamurabi); to add:
	go get Hamurabi
```

Maybe something missed getting checked in? I don't know how go does these things; all i know is that it did before and now it doesn't. It builds just fine on the master branch, so I'm pretty sure the breakage is due to changes on termenv-devel.

**Comment by dryack** [comment]
Hopefully better in https://github.com/dryack/go-hamurabi/commit/447b65dcb746491b16fcfe9725291139f61eadba?

**Comment by pomatias** [comment]
yeah that fixed it. thanks!
